name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # node 버전
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # key를 사용하여 node modules 캐싱
      - name: Cache node modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          # restore-keys 중에서 매칭되는 것이 있으면, 캐시에 있는 파일을 path에 복원
          restore-keys: ${{ runner.os }}-node-modules-

      - if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        name: Install packages
        # npm ci는 package-lock 파일 기반으로 설치(쓰기 권한 없음) -> npm install보다 빠르다.
        # 단, node_modules를 삭제하고 의존성을 한번에 설치함 -> 시간 지연 가능성이 있으므로 캐시 hit인 경우에만 그대로 사용
        run: npm ci

      - name: Build
        run: npm run build
